const BROWSER_GLOBALS = {
  chrome: "readonly",
  self: "readonly",
  globalThis: "readonly",
  window: "readonly",
  document: "readonly",
  navigator: "readonly",
  location: "readonly",
  history: "readonly",
  localStorage: "readonly",
  sessionStorage: "readonly",
  fetch: "readonly",
  console: "readonly",
  setTimeout: "readonly",
  clearTimeout: "readonly",
  setInterval: "readonly",
  clearInterval: "readonly",
  requestAnimationFrame: "readonly",
  cancelAnimationFrame: "readonly",
  AbortController: "readonly",
  AbortSignal: "readonly",
  MutationObserver: "readonly",
  IntersectionObserver: "readonly",
  Node: "readonly",
  NodeFilter: "readonly",
  XPathResult: "readonly",
  Element: "readonly",
  HTMLElement: "readonly",
  HTMLInputElement: "readonly",
  HTMLTextAreaElement: "readonly",
  HTMLSelectElement: "readonly",
  HTMLButtonElement: "readonly",
  Event: "readonly",
  CustomEvent: "readonly",
  MouseEvent: "readonly",
  PointerEvent: "readonly",
  KeyboardEvent: "readonly",
  InputEvent: "readonly",
  ClipboardEvent: "readonly",
  DragEvent: "readonly",
  Touch: "readonly",
  TouchEvent: "readonly",
  DataTransfer: "readonly",
  File: "readonly",
  Blob: "readonly",
  FileReader: "readonly",
  URL: "readonly",
  FormData: "readonly",
  Headers: "readonly",
  Response: "readonly",
  Request: "readonly",
  atob: "readonly",
  btoa: "readonly",
  createImageBitmap: "readonly",
  OffscreenCanvas: "readonly",
  MediaRecorder: "readonly",
  customElements: "readonly",
  ShadowRoot: "readonly",
  performance: "readonly",
  crypto: "readonly",
  indexedDB: "readonly",
  IDBKeyRange: "readonly",
  caches: "readonly",
  CSS: "readonly",
  DOMParser: "readonly",
  XMLSerializer: "readonly",
  TextDecoder: "readonly",
  TextEncoder: "readonly",
  XMLHttpRequest: "readonly",
};

export default [
  {
    files: ["extension/**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: BROWSER_GLOBALS,
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": ["warn", { "argsIgnorePattern": "^_", "varsIgnorePattern": "^_" }],
      "no-unreachable": "error",
      "no-duplicate-case": "error",
    },
  },
];
